# Generated by Django 3.1.7 on 2021-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_remove_contact_date_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=10)),
                ('stock', models.IntegerField(max_length=255)),
                ('image_url', models.ImageField(upload_to='')),
            ],
        ),
    ]
